version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: "mysql_db"
    restarts: always
    environment:
      MYSQL_ROOT_PASSWORD=root
      MYSQL_DATABASE=Attention
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    build: "./server"
    container_name: "fastapi_server"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=Attention
  
  client:
    build: "./client"
    container_name: "react_container"
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - VITE_API_BASE=http://localhost:8000
  
volumes:
  db_data: